### PR TITLE
Added showUser call which retrieves a user's profile using the …

### PR DESCRIPTION
**Pull request by ferdil**
…Twitter REST API

Since I wanted to get a bit more info about the logged in user, the users/show API provides all the known published info from the logged in user's profile.
 
This can be extended to allows a call to any of Twitter's REST API's

### CODE REVIEW

**Comment by TheBosZ** [comment]
Great! Thanks!

**Comment by campsjos** [comment]
Please, can you update the NPM package to get this feature using `npm install cordova-twitter-connect ...` or show in the docs how to get the last version downloading if from GitHub?

I was receving the error `TwitterConnect.showUser() is not a function` and thinking it was my fault until I digged in the code :)

Good work to both of you!

**Comment by ferdil** [comment]
If you're getting that error, then it means that the file TwitterConnect.js (from the www folder) hasn't been merged through to Cordova. Make sure that you have the correct version of this file (It has the extra showUser() function at the end (See [https://github.com/ManifestWebDesign/twitter-connect-plugin/blob/master/www/TwitterConnect.js](url))

**Comment by TheBosZ** [comment]
I've pushed this update to npm. You should now get the latest version using the normal install method.

I've also added a note in the installation section about how to install a plugin from the git url. You can just do:

`cordova plugin add https://github.com/ManifestWebDesign/twitter-connect-plugin --variable FABRIC_KEY=<Fabric API Key>`

**Comment by campsjos** [comment]
Fine!

**Pull request merged**
